# shellcheck shell=bash

# Long-running single-node 8-GPU LeRobot profile for SmolVLA fine-tuning.
# This is the first "real experiment" profile, not a 2-step smoke.

export EMBODIED_REPO_ROOT="${EMBODIED_REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"

export LEROBOT_DATASET_REPO_ID="${LEROBOT_DATASET_REPO_ID:-lerobot/svla_so100_pickplace}"
export LEROBOT_DATASET_ROOT="${LEROBOT_DATASET_ROOT:-$EMBODIED_REPO_ROOT/data/lerobot/svla_so100_pickplace}"
export LEROBOT_DATASET_VIDEO_BACKEND="${LEROBOT_DATASET_VIDEO_BACKEND:-pyav}"
export LEROBOT_DATASET_EVAL_SPLIT="${LEROBOT_DATASET_EVAL_SPLIT:-}"

export LEROBOT_POLICY_TYPE="${LEROBOT_POLICY_TYPE:-smolvla}"
export LEROBOT_POLICY_REPO_ID="${LEROBOT_POLICY_REPO_ID:-local/svla_so100_smolvla_8gpu_long}"
export LEROBOT_POLICY_PUSH_TO_HUB="${LEROBOT_POLICY_PUSH_TO_HUB:-false}"
export LEROBOT_POLICY_DEVICE="${LEROBOT_POLICY_DEVICE:-cuda}"
export LEROBOT_POLICY_PRETRAINED_PATH="${LEROBOT_POLICY_PRETRAINED_PATH:-$EMBODIED_REPO_ROOT/models/lerobot/smolvla/smolvla_base}"
export LEROBOT_POLICY_DTYPE="${LEROBOT_POLICY_DTYPE:-bfloat16}"
export LEROBOT_POLICY_ENABLE_GRADIENT_CHECKPOINTING="${LEROBOT_POLICY_ENABLE_GRADIENT_CHECKPOINTING:-true}"

# Per-process batch size. Effective batch size = LEROBOT_BATCH_SIZE * LEROBOT_NUM_PROCESSES.
export LEROBOT_STEPS="${LEROBOT_STEPS:-20000}"
export LEROBOT_BATCH_SIZE="${LEROBOT_BATCH_SIZE:-8}"
export LEROBOT_NUM_WORKERS="${LEROBOT_NUM_WORKERS:-4}"
export LEROBOT_PREFETCH_FACTOR="${LEROBOT_PREFETCH_FACTOR:-4}"
export LEROBOT_PERSISTENT_WORKERS="${LEROBOT_PERSISTENT_WORKERS:-true}"
export LEROBOT_LOG_FREQ="${LEROBOT_LOG_FREQ:-50}"
export LEROBOT_SAVE_CHECKPOINT="${LEROBOT_SAVE_CHECKPOINT:-true}"
export LEROBOT_SAVE_FREQ="${LEROBOT_SAVE_FREQ:-1000}"
export LEROBOT_SEED="${LEROBOT_SEED:-1002}"

# Keep simulator eval disabled for long offline fine-tuning. Enable eval_split/eval_steps explicitly later.
export LEROBOT_ENV_EVAL_FREQ="${LEROBOT_ENV_EVAL_FREQ:-0}"
export LEROBOT_EVAL_STEPS="${LEROBOT_EVAL_STEPS:-0}"
export LEROBOT_MAX_EVAL_SAMPLES="${LEROBOT_MAX_EVAL_SAMPLES:-}"
export LEROBOT_WANDB_ENABLE="${LEROBOT_WANDB_ENABLE:-false}"

export LEROBOT_RUN_NAME="${LEROBOT_RUN_NAME:-svla_so100_smolvla_8gpu_long}"
export LEROBOT_RUN_ROOT="${LEROBOT_RUN_ROOT:-$EMBODIED_REPO_ROOT/runs/lerobot}"
export TORCH_HOME="${TORCH_HOME:-$EMBODIED_REPO_ROOT/hf_cache/torch}"

# Accelerate launcher. Single-node 8-GPU by default; multi-node can override these.
export LEROBOT_NUM_PROCESSES="${LEROBOT_NUM_PROCESSES:-8}"
export LEROBOT_NUM_MACHINES="${LEROBOT_NUM_MACHINES:-1}"
export LEROBOT_MACHINE_RANK="${LEROBOT_MACHINE_RANK:-0}"
export LEROBOT_MAIN_PROCESS_IP="${LEROBOT_MAIN_PROCESS_IP:-127.0.0.1}"
export LEROBOT_MAIN_PROCESS_PORT="${LEROBOT_MAIN_PROCESS_PORT:-29501}"
export LEROBOT_ACCELERATE_MIXED_PRECISION="${LEROBOT_ACCELERATE_MIXED_PRECISION:-bf16}"

# Resume support:
#   export LEROBOT_RESUME=1
#   export LEROBOT_RESUME_CONFIG_PATH=runs/lerobot/<run>/<id>/lerobot_output/checkpoints/<step>/train_config.json
export LEROBOT_RESUME="${LEROBOT_RESUME:-0}"
export LEROBOT_RESUME_CONFIG_PATH="${LEROBOT_RESUME_CONFIG_PATH:-}"
